spring:
  datasource:
    url: jdbc:mysql://localhost:5508/sfg_prod?serverTimezone=UTC
    username: sfg_prod_user
    password: prod_pass
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: mysql
    show-sql: false
